Days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    - Sunday
Time:
    - '22:40'
Nomenclature:
    Monday: M
    Tuesday: T
    Wednesday: W
    Thursday: R
    Friday: F
    Saturday: S
    Sunday: U